-- INSERT INTO Dept. (name)
-- VALUES ('English'),
--        ('Computer Science'),
--        ('Physics'),
--        ('Biology'),
--        ('Art');

-- INSERT INTO role (title, salary, department_id)
-- VALUES ('ENG Lecturer', 50000, 1),
--        ('ENG Asst. Prof.', 70000, 1),
--        ('ENG Research Prof.', 80000, 1),
--        ('ENG Dept. Chair', 90000, 1),
--        ('ENG Dean', 110000, 1),
--        ('ENG Teaching Asst.', 30000, 1),
--        ('ENG Pgm. Coordinator', 60000, 1),
--        ('COMPSCI Lecturer', 50000, 2),
--        ('COMPSCI Asst. Prof.', 70000, 2),
--        ('COMPSCI Research Prof.', 80000, 2),
--        ('COMPSCI Dept. Chair', 90000, 2),
--        ('COMPSCI Dean', 110000, 2),
--        ('COMPSCI Teaching Asst.', 30000, 2),
--        ('COMPSCI Pgm. Coordinator', 60000, 2),
--        ('PHYS Lecturer', 50000, 3),
--        ('PHYS Asst. Prof.', 70000, 3),
--        ('PHYS Research Prof.', 80000, 3),
--        ('PHYS Dept. Chair', 90000, 3),
--        ('PHYS Dean', 110000, 3),
--        ('PHYS Teaching Asst.', 30000, 3),
--        ('PHYS Pgm. Coordinator', 60000, 3),
--        ('BIOL Lecturer', 50000, 4),
--        ('BIOL Asst. Prof.', 70000, 4),
--        ('BIOL Research Prof.', 80000, 4),
--        ('BIOL Dept. Chair', 90000, 4),
--        ('BIOL Dean', 110000, 4),
--        ('BIOL Teaching Asst.', 30000, 4),
--        ('BIOL Pgm. Coordinator', 60000, 4),
--        ('ART Lecturer', 50000, 5),
--        ('ART Asst. Prof.', 70000, 5),
--        ('ART Research Prof.', 80000, 5),
--        ('ART Dept. Chair', 90000, 5),
--        ('ART Dean', 110000, 5),
--        ('ART Teaching Asst.', 30000, 5),
--        ('ART Pgm. Coordinator', 60000, 5);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ('Robert', 'Clark', 9, ),
        ('Patricia', 'Lewis', 10, ),
        ('William', 'Walker', 11, ),
        ('Elizabeth', 'Hall', 12, 13),
        ('Richard', 'Allen', 13, ),
        ('Jennifer', 'Young', 14, ),
        ('Charles', 'King', 15, ),
        ('Jessica', 'Wright', 16, ),
        ('Daniel', 'Scott', 17, ),
        ('Amanda', 'Green', 18, ),
        ('Matthew', 'Adams', 19, ),
        ('Megan', 'Baker', 20, ),
        ('Anthony', 'Nelson', 21, ),
        ('Stephanie', 'Carter', 22, ),
        ('Joshua', 'Mitchell', 23, ),
        ('Nicole', 'Perez', 24, ),
        ('Andrew', 'Turner', 25, ),
        ('Rachel', 'White', 26, ),
        ('Thomas', 'Harris', 27, ),
        ('Angela', 'Hill', 28, ),
        ('Brian', 'Lopez', 29, ),
        ('Michelle', 'Young', 30, ),
        ('Kevin', 'Robinson', 31, ),
        ('Emily', 'King', 32, ),
        ('Mark', 'Edwards', 33, ),
        ('Samantha', 'Brooks', 34, ),
        ('Stephen', 'Nelson', 35, )
        ('John', 'Smith', 36, ),
        ('Emily', 'Johnson', 37, ),
        ('Michael', 'Williams', 38, ),
        ('Sarah', 'Brown', 39, ),
        ('David', 'Jones', 40, ),
        ('Laura', 'Garcia', 41, ),
        ('James', 'Martinez', 42, ),
        ('Linda', 'Robinson', 43, ),;
            
